name: Testing-Branch-Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        run: |
          git clone https://github.com/poojithareddypuli/Demo.git
          cd Demo
          git checkout main
          echo "Running tests or build"

      - name: Check if branch is 'testing'
        id: check_branch
        run: |
          echo "Checking if the current branch is 'main'..."
          if ($env:GITHUB_REF -ne 'refs/heads/test') {
            echo "This workflow should only run on the 'main' branch."
            exit 1
          } else {
            echo "Branch is 'main'. Proceeding with the workflow." }

      - name: Run build steps
        if: steps.check_branch.outcome == 'success'
        run: echo "Running the build steps for the 'main' branch..."
