name: Branch-Specific-Workflow

on:
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on:
      group: cvs-linux-self-hosted
    env:
      PUSH_PACKAGES: ${{ github.ref != 'refs/heads/testing' }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "Running tests"
